spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: krya
    url: jdbc:postgresql://localhost:5432/practice_webclient
  application:
    name: course-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9000
  servlet:
    context-path: /course-service

